/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/humanistic': RouteRecordInfo<
      '/albums/humanistic',
      '/albums/humanistic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/stars': RouteRecordInfo<
      '/albums/stars',
      '/albums/stars',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/七律·忆初试': RouteRecordInfo<
      '/posts/七律·忆初试',
      '/posts/%E4%B8%83%E5%BE%8B%C2%B7%E5%BF%86%E5%88%9D%E8%AF%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/七言·暖秋': RouteRecordInfo<
      '/posts/七言·暖秋',
      '/posts/%E4%B8%83%E8%A8%80%C2%B7%E6%9A%96%E7%A7%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/七言·秋夜独行梦归乡': RouteRecordInfo<
      '/posts/七言·秋夜独行梦归乡',
      '/posts/%E4%B8%83%E8%A8%80%C2%B7%E7%A7%8B%E5%A4%9C%E7%8B%AC%E8%A1%8C%E6%A2%A6%E5%BD%92%E4%B9%A1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/关于世界语': RouteRecordInfo<
      '/posts/关于世界语',
      '/posts/%E5%85%B3%E4%BA%8E%E4%B8%96%E7%95%8C%E8%AF%AD',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/关于评论的公告': RouteRecordInfo<
      '/posts/关于评论的公告',
      '/posts/%E5%85%B3%E4%BA%8E%E8%AF%84%E8%AE%BA%E7%9A%84%E5%85%AC%E5%91%8A',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/冷雨夜': RouteRecordInfo<
      '/posts/冷雨夜',
      '/posts/%E5%86%B7%E9%9B%A8%E5%A4%9C',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/各种测试': RouteRecordInfo<
      '/posts/各种测试',
      '/posts/%E5%90%84%E7%A7%8D%E6%B5%8B%E8%AF%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/喂鱼': RouteRecordInfo<
      '/posts/喂鱼',
      '/posts/%E5%96%82%E9%B1%BC',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/声声慢·重阳': RouteRecordInfo<
      '/posts/声声慢·重阳',
      '/posts/%E5%A3%B0%E5%A3%B0%E6%85%A2%C2%B7%E9%87%8D%E9%98%B3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/方寸暇思集': RouteRecordInfo<
      '/posts/方寸暇思集',
      '/posts/%E6%96%B9%E5%AF%B8%E6%9A%87%E6%80%9D%E9%9B%86',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/江城子·乙巳九月十六日梦臆': RouteRecordInfo<
      '/posts/江城子·乙巳九月十六日梦臆',
      '/posts/%E6%B1%9F%E5%9F%8E%E5%AD%90%C2%B7%E4%B9%99%E5%B7%B3%E4%B9%9D%E6%9C%88%E5%8D%81%E5%85%AD%E6%97%A5%E6%A2%A6%E8%87%86',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/虞美人—东风凌月明青池': RouteRecordInfo<
      '/posts/虞美人—东风凌月明青池',
      '/posts/%E8%99%9E%E7%BE%8E%E4%BA%BA%E2%80%94%E4%B8%9C%E9%A3%8E%E5%87%8C%E6%9C%88%E6%98%8E%E9%9D%92%E6%B1%A0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/西江月·八月廿三记景': RouteRecordInfo<
      '/posts/西江月·八月廿三记景',
      '/posts/%E8%A5%BF%E6%B1%9F%E6%9C%88%C2%B7%E5%85%AB%E6%9C%88%E5%BB%BF%E4%B8%89%E8%AE%B0%E6%99%AF',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/西江月·结营有感': RouteRecordInfo<
      '/posts/西江月·结营有感',
      '/posts/%E8%A5%BF%E6%B1%9F%E6%9C%88%C2%B7%E7%BB%93%E8%90%A5%E6%9C%89%E6%84%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/观星者之死': RouteRecordInfo<
      '/posts/观星者之死',
      '/posts/%E8%A7%82%E6%98%9F%E8%80%85%E4%B9%8B%E6%AD%BB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/觉前暇思': RouteRecordInfo<
      '/posts/觉前暇思',
      '/posts/%E8%A7%89%E5%89%8D%E6%9A%87%E6%80%9D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/鹊桥仙-燕飞伴云': RouteRecordInfo<
      '/posts/鹊桥仙-燕飞伴云',
      '/posts/%E9%B9%8A%E6%A1%A5%E4%BB%99-%E7%87%95%E9%A3%9E%E4%BC%B4%E4%BA%91',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/esperanto-day-1': RouteRecordInfo<
      '/posts/esperanto-day-1',
      '/posts/esperanto-day-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/esperanto-day-2': RouteRecordInfo<
      '/posts/esperanto-day-2',
      '/posts/esperanto-day-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Mijia-Web-Manager': RouteRecordInfo<
      '/posts/Mijia-Web-Manager',
      '/posts/Mijia-Web-Manager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/python-原神启动': RouteRecordInfo<
      '/posts/python-原神启动',
      '/posts/python-%E5%8E%9F%E7%A5%9E%E5%90%AF%E5%8A%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.8_d605b7048e33467f1b396db36d16d220/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@1.0.0-rc.8_@babel+pa_a076aeca96c7b5d092c958ffa05ad806/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/index.md': {
      routes:
        | '/albums/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/humanistic.md': {
      routes:
        | '/albums/humanistic'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/stars.md': {
      routes:
        | '/albums/stars'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.8_d605b7048e33467f1b396db36d16d220/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.8_d605b7048e33467f1b396db36d16d220/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/七律·忆初试.md': {
      routes:
        | '/posts/七律·忆初试'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/七言·暖秋.md': {
      routes:
        | '/posts/七言·暖秋'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/七言·秋夜独行梦归乡.md': {
      routes:
        | '/posts/七言·秋夜独行梦归乡'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/关于世界语.md': {
      routes:
        | '/posts/关于世界语'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/关于评论的公告.md': {
      routes:
        | '/posts/关于评论的公告'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/冷雨夜.md': {
      routes:
        | '/posts/冷雨夜'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/各种测试.md': {
      routes:
        | '/posts/各种测试'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/喂鱼.md': {
      routes:
        | '/posts/喂鱼'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/声声慢·重阳.md': {
      routes:
        | '/posts/声声慢·重阳'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/方寸暇思集.md': {
      routes:
        | '/posts/方寸暇思集'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/江城子·乙巳九月十六日梦臆.md': {
      routes:
        | '/posts/江城子·乙巳九月十六日梦臆'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/虞美人—东风凌月明青池.md': {
      routes:
        | '/posts/虞美人—东风凌月明青池'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/西江月·八月廿三记景.md': {
      routes:
        | '/posts/西江月·八月廿三记景'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/西江月·结营有感.md': {
      routes:
        | '/posts/西江月·结营有感'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/观星者之死.md': {
      routes:
        | '/posts/观星者之死'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/觉前暇思.md': {
      routes:
        | '/posts/觉前暇思'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/鹊桥仙-燕飞伴云.md': {
      routes:
        | '/posts/鹊桥仙-燕飞伴云'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/esperanto-day-1.md': {
      routes:
        | '/posts/esperanto-day-1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/esperanto-day-2.md': {
      routes:
        | '/posts/esperanto-day-2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Mijia-Web-Manager.md': {
      routes:
        | '/posts/Mijia-Web-Manager'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/python-原神启动.md': {
      routes:
        | '/posts/python-原神启动'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
